### ISSUE TITLE
AntiSpesh Module

### ISSUE THREAD

**Issue by iBuyMountainDew** [OccultMC/OCT-Hack#3]
**Is your feature request related to a problem? Please describe.**
The problem is that you're a spesh, I think an AntiSpesh module would be a great addition.

**Describe the solution you'd like**
This module will transcend the instance of the client to the realm of the Gods, allowing it to eliminate this client from existence, deleting it from all the machines it can be found on.

**Additional context**
You hella gay lol can't skid a json

**Comment by iBuyMountainDew** [comment]
also this is pretty cwl :p

https://dqs.dewy.dev

**Comment by ollieobama** [comment]
yes please add
